#!/usr/bin/env bash
# Installs Nginx on my server

sudo apt-get -y update
sudo apt-get -y install nginx

#sudo mv /usr/share/nginx/html/index.html /usr/share/nginx/html/index.txt
#sudo echo "Hello World!" > /usr/share/nginx/html/index.html
#sudo service nginx restart

sudo ufw allow 'Nginx HTTP'
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo service nginx restart
