#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
sudo pt-get -y update
sudo apt-get -y install haproxy
echo '  listen load_balancer
	bind *:80
	mode http
	balance roundrobin
	option httpclose
	option forwardfor
	server 440491-web-01 34.232.78.88:80 check 
	server 440491-web-02 54.237.19.219:80 check' | sudo tee /etc/haproxy/haproxy.cfg
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
service haproxy start
