#!/usr/bin/env bash
# a Bash script that displays To infinity and beyond indefinitely

# handle SIGTERM
trap 'echo "I am invicible!!!"' SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done

