#!/usr/bin/env bash
# script that displays numbers from 1 to 100 and prints FizzBuzz

a=0

while [ $a -le 100 ]
do
	if [ $((a%5)) -eq 0 ] && [ $((a%3)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((a%3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((a%5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$a"
	fi
	a=$((a+1))
done

