#!/usr/bin/env bash
# This script is displaying numbers to 20
# the string "bad luck from China" in the 4th loop
# the string "bad luck from Japan" in the 9th loop
# the string "bad luck from Italy" in the 17th loop

num=1
while [ $num -le 20 ]
do
	case $num in
		4)
			echo "4"
			echo "bad luck from China"
			;;
		9)
			echo "9"
			echo "bad luck from Japan"
			;;
		17)
			echo "17"
			echo "bad luck from Italy "
			;;
		*)
			echo "$num"
			;;
	esac
	num=$(( num + 1 ))
done

