#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
#display hours from 0 to 12
#display minutes from 1 to 59

time=0

while [ $time -lt 13 ]
do
	echo "Hour: $time "
	i=1
	while [ $i -le 59 ]
	do
		echo "$i"
		i=$((i+1))
	done
	time=$((time+1))
done
