#!/usr/bin/env bash

# configure a brand new Ubuntu machine to the requirements asked in this task installing Nginx

apt-get update
apt-get install -y nginx
touch /var/www/html/index.html /var/www/html/404.html
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

echo "server {
        listen 80;
        listen [::]:80;

        server_name _;

        error_page 404 /404.html;
        add_header X-Served-By $HOSTNAME;

        location / {
            root /var/www/html;
            index index.html;
        }

        location /redirect_me {
            return 301 https://github.com/AaronPeterOcen;
        }

        location /404 {
            root /var/www/html;
            internal;
        }
}"